APP_TOKEN_CACHE_KEY: APP_TOKEN_CACHE_KEY

MONGODB_CONFIG:
  name: 'fast_gateway_test' # 自定义次数据库链接名称
  type: 'mongodb' # 数据库链接类型
  url: 'mongodb://localhost:27017' # 数据库链接地址
  username: 'root' # 数据库链接用户名
  password: '123456' # 数据库链接密码
  database: 'fast_gateway_test' # 数据库名
  entities: 'mongo' # 自定义加载类型
  logging: false # 数据库打印日志
  synchronize: true # 是否开启同步数据表功能

MYSQL_CONFIG:
  name: 'nest-admin'
  type: 'mysql'
  host: 'localhost'
  port: 3306
  username: 'root'
  password: '123456'
  database: 'nest-admin'
  entities: 'mysql' # 这里的命名一定要跟 MongoDB 里面的配置命名区分开
  synchronize: true

REDIS_CONFIG:
  host: 'localhost' # redis 链接
  port: 6379 # redis 端口
  auth: '123456' # redis 连接密码
  db: 1 # redis 数据库

TEST_VALUE:
  name: 'test-value'

LOGGER_CONFIG:
  dir: 'logs'
  maxFileSize: 2m
  maxFiles: 15d
  errorLogName: 'common-error.log'
  appLogName: 'web.log'

JWT_CONFIG:
  secret: 'admin123456'